### PR TITLE
PLATEXP-3129: Enable bullet lists

### PR DESCRIPTION
**Pull request by ssalinas24**
JIRA: https://rackspace.atlassian.net/browse/PLATEXP-3129

This PR removes the list style properties from ordered and unordered lists in order to allow bullets to display again.

### CODE REVIEW

**Comment by ssalinas24** [comment]
@nicko-winner So the style source is coming from this line
https://github.com/rackerlabs/docs-landing-page/blob/dd7e640d8f338d616acff562e36dc5bf425eca90/layouts/partials/head.html#L24

How is that not already dynamic per URL?

**Review by nicko-winner — APPROVED** [review]
in `config.toml` the is a variable called: `relativeURLs = false`, if it was set to true, it might allow get hugo to use URL of the current site for its assets. [ref](https://gitlab.com/pages/hugo/-/issues/7#note_366975689) and [here](https://gohugo.io/content-management/urls/#relative-urls)

Might be worth exploring if you want to see what what this change will look like on all docs pages.

**Comment by ssalinas24** [comment]
@nicko-winner  I finally got back around to looking at this PR again. I Enabled the relative URLs, but the link html head element still points the CSS asset to docs.rackspace.com. Likely because relativeUrl only affects the content URLs.

In the browser I use this PR deploy preview, then go to another section of docs, https://deploy-preview-343--docs-landing-page.netlify.app/docs/sddc/sddc-business-handbook/about-sddc-business# , since that those pages are on a different repo and netlify site. I edit the HTML href on that page to just be `/styles.css`. 
Screen Shot 2023-02-15 at 3 19 23 PM

**Comment by ssalinas24** [comment]
Nick and I researched the relative URL and path changes to see if we could achieve a long term code change that would allow deploy previews across the other netlify doc repos to show master layout/style changes. However, it seems a little more complicated than a quick fix. So I have tested these changes manually by going to other page routes while keeping this deploy-preview-343 at the start and manually editing the html head to point to a relative `/styles.css` to validate these changes will work. Ultimately we will only see these changes take affect after merging to production.

**Pull request merged**
